spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faqdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /res
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 30m
